version: '3.2'

services:
  mosquitto:
    image: eclipse-mosquitto:1.6
    ports:
      - 1883:1883

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
    - 9090:9090
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    volumes:
    - ./docker/config/prometheus.yml:/etc/prometheus/prometheus.yml:ro